### ISSUE TITLE
remove 1 row of plots and show plot data vs prediciton

### ISSUE THREAD

**Issue by wseis** [technologiestiftung/flusshygiene#255]
currently we produce 5 plots. As I do not like to the plot "Modelimplikations", I suggest reducing the number of plat to 4. Then we would not have this empty plot window at the end.

Moreover, the most important plot,namely, Modelbewertung gegen Messwerte, is missing. Is it a problem of the R package or of the frontend?

**Comment by fabianmoronzirfas** [comment]
> Moreover, the most important plot,namely, Modelbewertung gegen Messwerte, is missing. Is it a problem of the R package or of the frontend?

R Package. I just display all plots that are added to a model

**Comment by hsonne** [comment]
> Moreover, the most important plot,namely, Modelbewertung gegen Messwerte, is missing.

I tried to open the plot URLs manually in Firefox and found out that the plot "[Modelbewertung gegen Messwerte](https://flsshygn-pgapi-uploads-dev.s3.eu-central-1.amazonaws.com/users/8/bathingspots/46/models/18/upload/plot/b69e848d2e5c0b8de9e10bf3233f68e1-1586449385284.svg)" does not open up in Firefox but (after user confirmation) in Microsoft Explorer. There is also a difference in the image property "contentType" that is stored in the database and I think that these phenomena are related to each other:

```
  id plotfiles.id                                  plotfiles.title plotfiles.metaData.mimetype plotfiles.metaData.contentType
1 18           37                 Überblick über getestete Modelle               image/svg+xml                  image/svg+xml
2 18           38            Datenqualität und Kalibrationsbereich               image/svg+xml                  image/svg+xml
3 18           39                   Modelbewertung gegen Messwerte               image/svg+xml       application/octet-stream
4 18           40 Perzentile auf Basis klassifizierter Datenpunkte               image/svg+xml                  image/svg+xml
```

I upload the svg file with the R function `httr::upload_file()` and I checked that this function sets the mime type (correctly, I assume) to "image/svg+xml" for all of the four svg files. This information seems to arrive correctly in the database but how can I influence the "contentType"? Or is this something that happens on the server side, @fabianmoronzirfas?

> I suggest reducing the number of plat to 4

In the current dev version, the plot "Modellimplikationen" is not created and uploaded any more.
I now upload only four svg images. Before, I uploaded six image files, five plots and one "empty plot" acting as a placeholder. @fabianmoronzirfas: Will there be a problem if there are only four plots? Do I need to upload two "empty plots" so that the frontend will always find six plots?

**Comment by fabianmoronzirfas** [comment]
> This information seems to arrive correctly in the database but how can I influence the "contentType"? 

The content type is [extracted from the file during upload](https://github.com/technologiestiftung/flusshygiene/blob/master/packages/postgres-api/src/lib/request-handlers/bathingspots/collections/post-file.ts#L33). We could make it controllable during upload, but there must be somthing different with the plot, if [multer](https://www.npmjs.com/package/multer-s3#setting-custom-content-type) (the upload module) detects it as a different type.

> Will there be a problem if there are only four plots? 

Nope. The [component that does the display](https://github.com/technologiestiftung/flusshygiene/blob/master/packages/cms-spa/src/components/spot/elements/Spot-Model-Plots.tsx) of the models just takes pairs of two plotfiles and displays them. If you add an even number it will show them

**Comment by hsonne** [comment]
I found no specific difference, calling the R function `mime::guess_type()` returns "image/svg+xml" for each of the created files (now only four, as proposed by @wseis)
```
> sapply(svg_files, mime::guess_type)
[1] "image/svg+xml" "image/svg+xml" "image/svg+xml" "image/svg+xml"
```
All files have a header that looks like this:
```
<?xml version='1.0' encoding='UTF-8' ?>
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' viewBox='0 0 576.00 432.00'>
<defs>
  <style type='text/css'><![CDATA[
    line, polyline, polygon, path, rect, circle {
      fill: none;
      stroke: #000000;
      stroke-linecap: round;
      stroke-linejoin: round;
      stroke-miterlimit: 10.00;
    }
  ]]></style>
</defs>
```
and they all end (properly, I assume) with
```
</svg>
```
I found the following issue: https://github.com/badunk/multer-s3/issues/97 Does it help?
Is it possible to explicitly set the content type to "svg" instead of letting multerS3 guess it in the line that you referenced:
```
contentType: multerS3.AUTO_CONTENT_TYPE,
```

**Comment by fabianmoronzirfas** [comment]
Hm. I can't hardcode the svg type, because the upload function is used on some other locations. I'll have to review that.

**Comment by fabianmoronzirfas** [comment]
s3Multer uses the [is-svg](https://github.com/sindresorhus/is-svg#readme). If the multer module can't determine that it is an [SVG we get the default contentType](https://github.com/badunk/multer-s3/blob/master/index.js#L36). Why is this one file not like the others?

**Comment by hsonne** [comment]
In multer-s3, `defaultContentType` results from a [call to the (unexported) function `staticValue()`](https://github.com/badunk/multer-s3/blob/168eb90c0f050760f791f1e97ced72253e01a6aa/index.js#L7-L14): 
```
function staticValue (value) {
  return function (req, file, cb) {
    cb(null, value)
  }
}

var defaultAcl = staticValue('private')
var defaultContentType = staticValue('application/octet-stream')
```
Is it possible to define this function in your script and to set
```
    contentType: staticValue('image/svg+xml'),
```
instead of
https://github.com/technologiestiftung/flusshygiene/blob/91921ac53cac324f92553c02b1dc301690314486/packages/postgres-api/src/lib/request-handlers/bathingspots/collections/post-file.ts#L33?
